version: 0.0
os: linux

files:
  - source: ./webapp/target/springbootdemo-0.0.1-SNAPSHOT.jar
    destination: /home/centos

hooks:
  AfterInstall:
<<<<<<< HEAD
    - location: ./afterInstall.sh
      timeout: 180
      runas: centos

=======
  - location: ./afterInstall.sh
    timeout: 180
    runas: centos
>>>>>>> fdf911ebe52dd919610ffeb0493e900d4b520cbb
