version: 0.0
os: linux

files:
  - source: ./webapp/target/springbootdemo-0.0.1-SNAPSHOT.jar
    destination: /home/centos

hooks:
  AfterInstall:
  - location: ./afterInstall.sh
    timeout: 180
    runas: centos
