version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
          sudo apt-get install python3
          curl -O https://bootstrap.pypa.io/get-pip.py
          python get-pip.py
          pip –version
          pip install awscli
          pip install awscli –upgrade
          aws --version
      - run:
          name: Run Test Case & Build Artifact
          command: |
            cd webapp
            mvn install
            cd target
            ls -al
            cd ../..
      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            ls -al
            mkdir -p codedeploy_artifact
            cp infrastructure/aws/codedeploy/*.sh .
            zip -r csye6225-web-app-${CIRCLE_BUILD_NUM}.zip webapp/target/springbootdemo-0.0.1-SNAPSHOT.jar *.sh *.yml
            ls -al
            mv csye6225-web-app-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/
            ls -al
            pwd
            cd codedeploy_artifact
            ls -al
            pwd
            cd ..
            pwd
            ls -al
      - run:
          name: Upload Artifact to S3
          command: |
            aws s3 cp "codedeploy_artifact/csye6225-web-app-${CIRCLE_BUILD_NUM}.zip" s3://code-deploy.csye6225-spring2019-liuzhe3.me/
      - run:
          name: Make CodeDeploy API call
          command: |
            aws deploy create-deployment --application-name csye6225-webapp --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name csye6225-webapp-deployment --s3-location bucket=code-deploy.csye6225-spring2019-liuzhe3.me,bundleType=zip,key=csye6225-web-app-${CIRCLE_BUILD_NUM}.zip