version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get install python3
            sudo curl -O https://bootstrap.pypa.io/get-pip.py
            sudo python get-pip.py
            sudo pip install awscli
            sudo pip install awscli --upgrade
            aws --version
      - run:
          name: Run Test Case & Build Artifact
          command: |
            cd webapp
            mvn install
            cd target
            ls -al
            cd ../..
      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            ls -al
            mkdir -p codedeploy_artifact
            cp infrastructure/aws/codedeploy/*.sh .
            zip -r csye6225-web-app-${CIRCLE_BUILD_NUM}.zip webapp/target/springbootdemo-0.0.1-SNAPSHOT.jar *.sh *.yml
            ls -al
            mv csye6225-web-app-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/
            ls -al
            pwd
            cd codedeploy_artifact
            ls -al
            pwd
            cd ..
            pwd
            ls -al
      - run:
          name: Upload Artifact to S3
          command: |
            aws s3 cp "codedeploy_artifact/csye6225-web-app-${CIRCLE_BUILD_NUM}.zip" s3://code-deploy.csye6225-spring2019-liuzhe3.me/
      - run:
          name: Make CodeDeploy API call
          command: |
            DOMAIN_NAME=$(aws route53 list-hosted-zones --query HostedZones[0].Name --output text)
            CD_DOMAIN="code-deploy."${DOMAIN_NAME%?}
            aws deploy create-deployment --application-name csye6225-webapp --deployment-config-name CodeDeployDefault.AllAtOnce --region us-east-1 --deployment-group-name csye6225-webapp-deployment --s3-location bucket=$CD_DOMAIN,bundleType=zip,key=csye6225-web-app-${CIRCLE_BUILD_NUM}.zip